/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BubblemapIndexImport } from './routes/bubblemap/index'
import { Route as LockMintImport } from './routes/lock/$mint'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BubblemapIndexRoute = BubblemapIndexImport.update({
  path: '/bubblemap/',
  getParentRoute: () => rootRoute,
} as any)

const LockMintRoute = LockMintImport.update({
  path: '/lock/$mint',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lock/$mint': {
      id: '/lock/$mint'
      path: '/lock/$mint'
      fullPath: '/lock/$mint'
      preLoaderRoute: typeof LockMintImport
      parentRoute: typeof rootRoute
    }
    '/bubblemap/': {
      id: '/bubblemap/'
      path: '/bubblemap'
      fullPath: '/bubblemap'
      preLoaderRoute: typeof BubblemapIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lock/$mint': typeof LockMintRoute
  '/bubblemap': typeof BubblemapIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lock/$mint': typeof LockMintRoute
  '/bubblemap': typeof BubblemapIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lock/$mint': typeof LockMintRoute
  '/bubblemap/': typeof BubblemapIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lock/$mint' | '/bubblemap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lock/$mint' | '/bubblemap'
  id: '__root__' | '/' | '/lock/$mint' | '/bubblemap/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LockMintRoute: typeof LockMintRoute
  BubblemapIndexRoute: typeof BubblemapIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LockMintRoute: LockMintRoute,
  BubblemapIndexRoute: BubblemapIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lock/$mint",
        "/bubblemap/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lock/$mint": {
      "filePath": "lock/$mint.tsx"
    },
    "/bubblemap/": {
      "filePath": "bubblemap/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
